### ISSUE TITLE
I can't see comments

### ISSUE THREAD

**Issue by floriansaul** [johnpc/book-club#1]
![Screenshot 2024-01-18 192619](https://github.com/johnpc/book-club/assets/9013010/0439b713-7980-4304-a514-b974ec9be645)

Chrome PC

I know I've seen the comments before because I remember leaving one, but I can't seem to see them right now

**Comment by johnpc** [comment]
I've removed the comments feature entirely in favor of a completely unauthenticated experience, so I'm closing this now

**Comment by floriansaul** [comment]
haha fair enough my poor comment
